name: Code Validator

on: [push, pull_request]

permissions:
  contents: read

jobs:
  name: Code Analysis
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10.10"
      - name: Install requir
      - name: Black
        uses: psf/black@stable
        with:
          safe: true
          preview: ture
          line-length: "121"
          include: '\.pyi?$'
          exclude: '\.git |\.__pycache__'
      - name: Flake8
        uses: py-actions/flake8@v2
        with:
          ignore: "E266,E501,W503"
          max-line-length: "121"
